
services:
  vidinie-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    networks:
      - vidinie-network
    ports:
      - "8000:8000"
    environment:
      - .env
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      # - mongodb
      - redis
    volumes:
      - ./temp:/app/temp
  vidinie-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    networks:
      - vidinie-network
    ports:
      - "3000:3000"
    environment:
      - .env
    depends_on:
      - vidinie-backend
  vidinie-celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    networks:
      - vidinie-network
    environment:
      - .env
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      # - mongodb
      - redis
    volumes:
      - ./temp:/app/temp
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    command: mongod --replSet rs0 --bind_ip_all
    
  mongodb-setup:
    image: mongo:latest
    depends_on:
      - mongodb
    restart: "no"
    entrypoint: >
      bash -c "
      sleep 2 &&
      mongosh --host mongodb:27017 --eval 'rs.initiate()'
      "

  redis:
    image: redis:7-alpine
    networks:
      - vidinie-network
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
networks:
  vidinie-network:
volumes:
  mongodb-data:
  redis-data: