version: '3.8'

services:
  vidinie-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    networks:
      - vidinie-network
    ports:
      - "8000:8000"
    environment:
      - .env
    depends_on:
      - mongodb
  vidinie-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    networks:
      - vidinie-network
    ports:
      - "3000:3000"
    environment:
      - .env
    depends_on:
      - backend
  mongodb:
    image: mongo
    networks:
      - vidinie-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
networks:
  vidinie-network: