# use base node image
FROM node:20-slim

# set working directory
WORKDIR /app

# copy package.json file
COPY package*.json /.

# install dependencies
RUN npm install

# copy frontend directory
COPY frontend/ .

# build frontend
RUN npm run build

# expose port 3000
EXPOSE 3000

# start frontendÍ
CMD ["npm", "run", "start"]