version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - .env
    depends_on:
      - mongodb
    networks:
      - vidgen-network
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - .env
    depends_on:
      - backend
    networks:
      - vidgen-network
  mongodb:
    image: mongodb/mongodb-community-server:8.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - type: bind
        source: ./mongodb_data
        target: /data/db
    networks:
      - vidgen-network
networks:
  - vidgen-network