# use base python image
FROM python:3.10-slim

# set working directory
WORKDIR /app

# copy requirements file
COPY requirements.txt .

# install dependencies
RUN pip install -r requirements.txt

# copy fonts directory
COPY fonts/ .

# copy core directory
COPY core/ .

# copy utils directory
COPY utils/ .

# copy api directory
COPY api/ .

# copy .env file
COPY .env .

# copy config.yaml file
COPY config.yaml .

# expose port 8000
EXPOSE 8000

# start server
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
