"""
JWT token verification for Better Auth tokens.
Supports both HS256 (symmetric) and EdDSA (asymmetric) algorithms.
"""
from typing import Dict, Optional
from core.utils.logger import get_logger
import jwt
from api.core.auth.config import BETTER_AUTH_SECRET
from api.core.auth.jwks import get_jwt_public_key
from api.core.auth.enums import JWTAlgorithm

logger = get_logger("auth.jwt_verifier")


def _decode_hs256_jwt(token: str) -> Optional[Dict]:
    """
    decode a HS256 jwt token using the better-auth secret.
    """
    try:
        decoded_token = jwt.decode(
            token,
            BETTER_AUTH_SECRET,
            algorithms=[JWTAlgorithm.HS256],
            options={"verify_aud": False}  # Disable audience verification
        )
        return decoded_token
    except Exception as e:
        logger.error(f"Error decoding HS256 JWT: {e}")
        return None


async def _decode_eddsa_jwt(kid: str, token: str) -> Optional[Dict]:
    """
    decode an EdDSA jwt token using the public key from the jwks cache.
    """
    if not kid:
        logger.error("EdDSA token missing key ID (kid)")
        return None
    
    public_key = await get_jwt_public_key(kid)
    if not public_key:
        logger.error(f"Public key not found for key ID: {kid}")
        return None
    
    try:
        # decode with public key
        # disable audience validation since backend is a separate service
        decoded_token = jwt.decode(
            token,
            public_key,
            algorithms=[JWTAlgorithm.ED25519],
            options={"verify_aud": False}  # Disable audience verification
        )
        return decoded_token
    except Exception as e:
        logger.error(f"Error decoding EdDSA JWT: {e}")
        return None


async def verify_better_auth_jwt(token: str) -> Optional[Dict]:
    """
    verify a jwt token generated by better-auth.
    returns the decoded token payload if valid, None if invalid or expired.
    """
    try:
        # decode header to get algorithm and key id
        unverified_header = jwt.get_unverified_header(token)
        alg = unverified_header.get("alg")
        kid = unverified_header.get("kid")        
        # check algorithm using enum values
        if alg == JWTAlgorithm.HS256:
            decoded_token = _decode_hs256_jwt(token)
        elif alg == JWTAlgorithm.ED25519:
            decoded_token = await _decode_eddsa_jwt(kid, token)
        else:
            logger.error(f"unsupported jwt algorithm: {alg}")
            return None
        return decoded_token
    except jwt.ExpiredSignatureError:
        logger.error("better-auth token expired")
        return None
    except jwt.InvalidTokenError as e:
        logger.error(f"better-auth token is invalid: {e}")
        return None
    except Exception as e:
        logger.error(f"error decoding better-auth jwt: {e}")
        return None

