import os
from typing import Dict, Optional
from core.utils.logger import get_logger
import jwt
from dotenv import load_dotenv
from fastapi import Request, HTTPException
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials

logger = get_logger("auth")
load_dotenv()

# better-auth jwt secret - should match BETTER_AUTH_SECRET from frontend
BETTER_AUTH_SECRET = os.getenv("BETTER_AUTH_SECRET")
JWT_ALGORITHM = os.getenv("JWT_ALGORITHM", "HS256")

if not BETTER_AUTH_SECRET:
    logger.warning("better-auth secret not found. jwt verification may fail.")


def verify_better_auth_jwt(token: str) -> Optional[Dict]:
    """
    verify a jwt token generated by better-auth.
    returns the decoded token payload if valid, None if invalid or expired.
    """
    try:
        decoded_token = jwt.decode(
            token,
            BETTER_AUTH_SECRET,
            algorithms=[JWT_ALGORITHM]
        )
        return decoded_token
    except jwt.ExpiredSignatureError:
        logger.error("better-auth token is expired")
        return None
    except jwt.InvalidTokenError as e:
        logger.error(f"better-auth token is invalid: {e}")
        return None
    except Exception as e:
        logger.error(f"error decoding better-auth jwt: {e}")
        return None


class BetterAuthBearer(HTTPBearer):
    """
    bearer authentication middleware for better-auth jwt tokens.
    replaces the old JWTBearer class to work with better-auth tokens.
    """
    def __init__(self, auto_error: bool = True):
        super(BetterAuthBearer, self).__init__(auto_error=auto_error)

    async def __call__(self, request: Request) -> str:
        """
        verify better-auth jwt token and return user ID.
        """
        credentials: HTTPAuthorizationCredentials | None = await super(BetterAuthBearer, self).__call__(request)
        if credentials:
            if not credentials.scheme == "Bearer":
                raise HTTPException(status_code=403, detail="Invalid authentication scheme")
            
            # verify the better-auth jwt token
            decoded_token = verify_better_auth_jwt(credentials.credentials)
            if not decoded_token:
                raise HTTPException(status_code=403, detail="Invalid or expired token")
            
            # extract user ID from token
            user_id = decoded_token.get("userId") or decoded_token.get("sub") or decoded_token.get("user_id")
            if not user_id:
                logger.error(f"user id not found in token: {decoded_token}")
                raise HTTPException(status_code=403, detail="Invalid token: user ID not found")
            
            return user_id
        else:
            raise HTTPException(status_code=403, detail="Invalid authentication credentials")
