# .github/workflows/stagingdeployments.yml
name: Test and Deploy Production Back-end Application

on:
  push:
    branches: [ production ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy to Production
        env:
          HOST: ${{secrets.PRODUCTION_HOST }}
          USER: ${{secrets.PRODUCTION_USER}}
          PASSWORD: ${{secrets.PRODUCTION_PASSWORD}}
          PATH: ${{secrets.PRODUCTION_API_PATH}}
        run: |
          sshpass -p "${PASSWORD}" ssh -o StrictHostKeyChecking=no ${USER}@${HOST} '
            cd ${PATH} &&
            git pull origin production && git checkout production &&
            docker-compose -f docker-compose.yml build &&
            docker-compose down &&
            docker-compose up -d
          '